import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Logos from "@/components/Logos";
import FooterLinks from "@/components/FooterLinks";

const inter = Inter({ subsets: ['latin'] })

// This page is just to display information for setting up your .env file
// Once you do that, this can be deleted
export default function PreSetupPage() {
    return (
        <>
            <Head>
                <title>Create Next App - PropelAuth version</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Logos />
                <div className={styles.center}>
                    <h3 className={inter.className}>
                        To get started, edit your <code>.env</code> file.
                    </h3>
                </div>
                <FooterLinks />
            </main>
        </>
    )
}
